version: "3"

services:
  php-cli:
    build:
      context: etc/devel/docker/php
    image: php/php-cli
    container_name: real-time.php-console
    volumes:
      - ".:/app"
    networks:
      real_time_net:
        ipv4_address: 172.19.1.2
    tty: true

  redis:
    image: redis:alpine
    container_name: real-time.redis
    ports:
      - 6379:6379
    networks:
      real_time_net:
        ipv4_address: 172.19.1.3
    tty: true

  mercure:
    image: dunglas/mercure
    container_name: real-time.mercure
    ports:
      - 80:80
    environment:
      - JWT_KEY=${MERCURE_JWT_TOKEN}
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=${MERCURE_PUBLISH_URL}
    networks:
      real_time_net:
        ipv4_address: 172.19.1.4
    tty: true

networks:
  real_time_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
